[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "alpaca-trade-api>=3.2.0",
    "flask>=3.1.1",
    "pandas>=2.2.3",
]
